### ISSUE TITLE
Strengthening Password Requirements

### ISSUE THREAD

**Issue by klinkoberstar** [uchicago-capp-30320/new-arrivals-chi#144]
Our current password policy mandates a minimum length of 8 characters, including a mix of upper and lower case letters, at least one symbol, and one number. We have considered of dual authentication; however, we're mindful of potential user frustration and added complexity; we are open to exploring this futher should advanced security be required. Additionally, we're also considering measures to block commonly used passwords in addition to our existing requirements.

**Comment by FedericoDM** [comment]
Closed with #160
