### ISSUE TITLE
Ensuring Secure Configuration with Authenticated Admin and General Users

### ISSUE THREAD

**Issue by klinkoberstar** [uchicago-capp-30320/new-arrivals-chi#147]
Our strategy involves ensuring that default credentials for authenticated users adhere to the least privilege principle. By minimizing unnecessary services and access privileges for non-administrative users, we will the risk of security misconfigurations.

**Comment by MadeleineKRoberts** [comment]
Given that we only have one level of authenticated user at this point, we are good. This will more so come into play once we have authenticated admin users, authenticated general users, and unauthenticated users

**Comment by klinkoberstar** [comment]
Closed with auth testing
