### ISSUE TITLE
follow up with resurrection project

### ISSUE THREAD

**Issue by klinkoberstar** [uchicago-capp-30320/new-arrivals-chi#15]
- Email resurrection project back with a time to meet for either this week or next
- Xiomara created a when2meet to see when most folks are avaliable: https://www.when2meet.com/?24542267-uTZAJ
- Remind folks to reply to when2meet on Thursday (?)

UPDATE:
- team said Monday afternoons are best for them
- email send on Wed evening, Kathryn followed up Friday am

**Comment by klinkoberstar** [comment]
XS

**Comment by klinkoberstar** [comment]
@xiomara0 to follow up again

**Comment by xiomara0** [comment]
Meeting for Monday, 4/22 @ 3pm
