### ISSUE TITLE
(bug): TemplateSyntaxError in health

### ISSUE THREAD

**Issue by klinkoberstar** [uchicago-capp-30320/new-arrivals-chi#165]
**Describe the bug**
TemplateSyntaxError
jinja2.exceptions.TemplateSyntaxError: expected token 'end of print statement', got 'else'

*A clear and concise description of what the bug is.*

**To Reproduce**

*Steps to reproduce the behavior:*

**Expected behavior**

*A clear and concise description of what you expected to happen.*

**Code Chunks**

*If applicable, add code chunks to help explain your problem.*

**Additional context**

*Add any other context about the problem here.*

**Comment by FedericoDM** [comment]
Closed by #150
