### ISSUE TITLE
Solidify features, based on user feedback.

### ISSUE THREAD

**Issue by klinkoberstar** [uchicago-capp-30320/new-arrivals-chi#3]
get feedback from team

**Comment by klinkoberstar** [comment]
- get feedback from team as well

M

**Comment by xiomara0** [comment]
https://docs.google.com/spreadsheets/d/1-zlTrd4wNLcXUcZ8mh8-HzmKQmrsRkkqYl1cUGY6DK0/edit#gid=0

**Comment by klinkoberstar** [comment]
To dicuss with team then close

**Comment by klinkoberstar** [comment]
@xiomara0 & @sumslong I think this will be an ongoing convo, but i think we can close this issue if you're comfortable! Don't want to close without your approval tho :)

**Comment by xiomara0** [comment]
gonna close! haha, I was wondering this myself since I don't like having open tasks. Like the satisfaction of closing this.
