### ISSUE TITLE
Set up meeting with James for support for longevity

### ISSUE THREAD

**Issue by klinkoberstar** [uchicago-capp-30320/new-arrivals-chi#37]

**Comment by xiomara0** [comment]
Emailed James - waiting response!

**Comment by xiomara0** [comment]
Got response - I think we should start with his recommendation of scoping out requirements and then asking for specific funding for it

**Comment by klinkoberstar** [comment]
Pasting here so we can always easily find it! 

Hi Xiomara & Kathryn,
 
I’m so glad to see that your project is being met with enthusiasm. It sounds like it could be a great resource for the city. The first thing to probably start doing is to check with those that have expressed interest if they have any budget to fund continued work. Even a small amount could go a long way at this phase, so it’s good to know who might be interested.

The other thing you can be doing at this phase is considering what it will take to keep this running, I know I spoke with other members of your team about reducing the operational costs (i.e. a person that can make changes via an admin is much easier to come by than a person that can modify a Python file).  Let’s keep talking about that as a technical priority for this project.

But more in that direction, would be an understanding of:

what the project is likely to need in terms of development after the quarter ends, i.e. what will it need to be 100% useful that you won’t have time to do in the confines of this course
What capacity/commitment will team members have. Is anyone willing to commit to staying actively involved after their time ends?
 
From there you can start to figure out a budget (in money and/or volunteer time) that it’ll take to maintain. I’m glad continue emailing or to meet anytime to discuss more.


Best,
James

(I want to be clear, in no way are my expectations of any of you to commit to working on this beyond graduation.  It will be important to understand what’s likely though. It is very tough to hand over a codebase, no matter the quality, without any team continuity.  If that is the direction it needs to go, we can talk about trying to find suitable maintainers sooner than later.)
