### ISSUE TITLE
Creating script for user feedback sessions

### ISSUE THREAD

**Issue by klinkoberstar** [uchicago-capp-30320/new-arrivals-chi#40]
- Creating script to standardize which features we test and which questions to ask
- See UI/UX material folder for an example script

**Comment by klinkoberstar** [comment]
Info in materials

right now thinking:
- legal assistance flow
- health flow

are there specific things the dev team wants to see:
- worried about video recording

**Comment by xiomara0** [comment]
English version ready: https://docs.google.com/document/d/1C6haJWzXFOplfo-SPLTwNmNKYCVlW3hwfMW4T1r8qNI/edit#heading=h.qwdkdljebtqi

I'm working on translating to Spanish this second half of the week.

**Comment by xiomara0** [comment]
Spanish version ready: https://docs.google.com/document/d/1KoNs27YnmFg6JtRTLjh1MW-G8ktM3Fe4l_5LMn894Zs/edit#heading=h.qwdkdljebtqi

Going to close out this task!
