### ISSUE TITLE
(bug): pre-commit linter does not automatically fix all issues

### ISSUE THREAD

**Issue by sumslong** [uchicago-capp-30320/new-arrivals-chi#56]
In the linter pre-commit, it does not automatically fix all bugs. For main.py, it did not automatically insert blank lines the first pass. Linter had to be ran multiple times before successfully linting.

**Comment by aaronhaefner** [comment]
Can you provide a more detailed example? I tried to replicate what you described with the following steps and could not (the linting and re-formatting is successful). I can repeatedly delete the line and run pre-commit and watch it work?

- git switch main
- deleted the last line of the `app/main.py` file
- poetry shell
- pre-commit run --all-files

My guess is that you staged the file, ran pre-commit, and then didn't stage the additional change (line addition) that happened. You can run the command before staging to avoid this. I updated the PR template to specify this.

**Comment by sumslong** [comment]
You're right-- I did not stage the additional change. I will be sure to run prior to staging. Thanks for updating the PR template!
