### ISSUE TITLE
Finalize Legal Flow design

### ISSUE THREAD

**Issue by klinkoberstar** [uchicago-capp-30320/new-arrivals-chi#58]
Kathryn + Xiomara, then share with team for feedback. Finalize mock up for frontend team (keep summer in the loop)

**Comment by klinkoberstar** [comment]
Kathryn/Xiomara to meet 4/24 @ 6

**Comment by klinkoberstar** [comment]
![Legal decision tree](https://github.com/uchicago-capp-30320/new-arrivals-chi/assets/111700741/9fa87d2f-dc2f-4199-acf0-b7408526427c)

https://lucid.app/lucidspark/56257806-111f-42ec-b862-6e1eea1ee454/edit?viewport_loc=-2036%2C-354%2C7561%2C4269%2C0_0&invitationId=inv_c4831409-cf88-4db9-aba4-f13f1c13360c

**Comment by xiomara0** [comment]
This looks good to me. Thanks for drawing this up! I can send out an email on Friday to resurrection project asking for feedback on this flow. Should we close it now or post-feedback? I'm good with either!

**Comment by klinkoberstar** [comment]
> This looks good to me. Thanks for drawing this up! I can send out an email on Friday to resurrection project asking for feedback on this flow. Should we close it now or post-feedback? I'm good with either!
> 
> Minor errors:
> 
> * Humanitarian Parole flow > "**iin** my home country"
> * Victim of crime/trafficking flow > **victime**

good catch! fixed. i'm going to close for now and we can reopen if/when we need to make edits!
