### ISSUE TITLE
Add pre-commit to readme

### ISSUE THREAD

**Issue by klinkoberstar** [uchicago-capp-30320/new-arrivals-chi#59]

**Comment by aaronhaefner** [comment]
Wondering if adding this to the PR template in #54 is sufficient? Otherwise I can add to a readme, but not sure where it makes most sense?

```
## Checklist before requesting a review
- [ ] pre-commit run --all-files (run before pushing)
- [ ] pytest if applicable
- [ ] Link issue
- [ ] Update relevant documentation if applicable: doc strings, readme, poetry.
```

**Comment by sumslong** [comment]
I like that format, @aaronhaefner . It has been very helpful! :-) I think that is sufficient, and I don't think it needs to be in the README.

**Comment by aaronhaefner** [comment]
Great - thanks for confirming. Should have gotten it in there a bit earlier!
