### ISSUE TITLE
Check & make hover buttons an appropriate shade

### ISSUE THREAD

**Issue by sumslong** [uchicago-capp-30320/new-arrivals-chi#99]

**Comment by xiomara0** [comment]
Using this tool to decide shade: https://mdigi.tools/color-shades/#9fc5f8

- Blue from #9fc5f8 --> #297def when hovered
- Yellow from #FFE599 --> #ffbe00 when hovered
- Green looks good
- Orange looks good! 

Will implement on 5/7 during the evening.
